## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.array([x for x in range(10)])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr[(arr>3)&(arr<8)]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [5]:
arr[(max(arr))]=0
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr1 = np.random.randint(-10,10,20)
arr2 = np.random.randint(-10,10,20)

print(f'arr1{arr1}')
print(f'arr2{arr2}')

arr1[ -4   9   5  -9   6  -4  -2  -8 -10  -7   1  -3   2  -4   1   7   7  -8
   9  -1]
arr2[  7   4   3   5  -8   2   2  -1   7   2   7   4 -10  -6   5  -3  -2  -2
  -9  -2]


In [20]:
new_arr = []
for x in arr1.ravel(): #arr1.ravel() - make a flat view of arr1
    temp_row = [] #make a temp row
    for y in arr2.ravel():
        temp_row.append(x*y)
    new_arr.append(temp_row)
final_result = np.array(new_arr)
final_result=final_result.reshape(arr1.size, arr2.size)
print(final_result)

[[-28 -16 -12 -20  32  -8  -8   4 -28  -8 -28 -16  40  24 -20  12   8   8
   36   8]
 [ 63  36  27  45 -72  18  18  -9  63  18  63  36 -90 -54  45 -27 -18 -18
  -81 -18]
 [ 35  20  15  25 -40  10  10  -5  35  10  35  20 -50 -30  25 -15 -10 -10
  -45 -10]
 [-63 -36 -27 -45  72 -18 -18   9 -63 -18 -63 -36  90  54 -45  27  18  18
   81  18]
 [ 42  24  18  30 -48  12  12  -6  42  12  42  24 -60 -36  30 -18 -12 -12
  -54 -12]
 [-28 -16 -12 -20  32  -8  -8   4 -28  -8 -28 -16  40  24 -20  12   8   8
   36   8]
 [-14  -8  -6 -10  16  -4  -4   2 -14  -4 -14  -8  20  12 -10   6   4   4
   18   4]
 [-56 -32 -24 -40  64 -16 -16   8 -56 -16 -56 -32  80  48 -40  24  16  16
   72  16]
 [-70 -40 -30 -50  80 -20 -20  10 -70 -20 -70 -40 100  60 -50  30  20  20
   90  20]
 [-49 -28 -21 -35  56 -14 -14   7 -49 -14 -49 -28  70  42 -35  21  14  14
   63  14]
 [  7   4   3   5  -8   2   2  -1   7   2   7   4 -10  -6   5  -3  -2  -2
   -9  -2]
 [-21 -12  -9 -15  24  -6  -6   3 -21  -6 -21 -12  30  18 -15   9

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [7]:
mass_A = np.random.randint(0, 10, (8, 3))
mass_B = np.random.randint(0, 10, (2, 2))

print(f"Matrix A: \n {mass_A}")
print(f"\nMatrix B: \n {mass_B}")

matching_rows = []
for i, row_a in enumerate(mass_A):
    for row_b in mass_B:
        if all(item in row_a for item in row_b):
            matching_rows.append(i) #if statement is True
            break



print(f"\n Rows in , matrix A that contain all elements from any row in matrix B: {matching_rows}")

Matrix A: 
 [[1 2 4]
 [3 3 7]
 [5 0 5]
 [3 4 7]
 [7 2 0]
 [8 5 2]
 [2 6 1]
 [5 9 7]]

Matrix B: 
 [[8 0]
 [0 5]]

 Rows in , matrix A that contain all elements from any row in matrix B: [2]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [8]:
matrix_one = np.random.randint(0, 3, (10, 3))
print(f'Starter matrix \n {matrix_one}')
filtered_matrix = matrix_one[np.max(matrix_one, axis=1) != np.min(matrix_one, axis=1)] #Filter of matrix
print(f'Matrix with out full duplicates values in one row \n {filtered_matrix}')

Starter matrix 
 [[2 0 1]
 [2 0 2]
 [1 0 0]
 [2 2 2]
 [1 2 1]
 [2 1 0]
 [2 2 0]
 [1 1 0]
 [0 1 1]
 [2 1 1]]
Matrix with out full duplicates values in one row 
 [[2 0 1]
 [2 0 2]
 [1 0 0]
 [1 2 1]
 [2 1 0]
 [2 2 0]
 [1 1 0]
 [0 1 1]
 [2 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [25]:
matrix_two = np.random.randint(0, 2, (10, 3))
print(f'base matrix : \n{matrix_two}')
unique_rows = np.unique(matrix_two, axis=0)

print(f"\nMatrix after deleting of duplicates rows: with final rows - {len(unique_rows)} from {len(matrix_two)}")
print(unique_rows)

base matrix : 
[[1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [0 1 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [1 0 1]]

Matrix after deleting of duplicates rows: with final rows - 6 from 10
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [18]:
'''First method without NumPy'''
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
final_sum = 1
for i in range(min(len(X), len(
        X[0]))):  #Get indexes of row ( In this example quantity columns should be equals of rows for calculation)
    if X[i][i] != 0:  #Checking if number not equal - 0
        final_sum *= X[i][i]
print(f'Sum by NumPy {final_sum}')

'''Second method without NumPy'''
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
more_then_0 = np.diag(X) != 0 #Get bool arrray
only_from_1 = np.diag(X)[more_then_0] #Get numbers more then 0 from diagonal
sum_diag = np.prod(only_from_1) #sum
print(f'Sum by Python {sum_diag}')


Sum by NumPy 3
Sum by Python 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [19]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

def check_func(x,y):
    result_numpy = np.array_equal(np.sort(np.array(x)), np.sort(np.array(y)))
    result_python = sorted(x) == sorted(y)
    return f'equals \n by NymPy - {result_numpy} \n by Python -  {result_python}'

print("Result:", check_func(x,y))

Result: equals 
 by NymPy - True 
 by Python -  True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [158]:
import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
#Search zero positions
''' Make a slice without last position - (It will help me with next 
calculation) Escape from error - Out of range'''
zero_position = np.where(x[:-1] == 0)[0]
# All position equals - 0, Last [0] - for 'cleaning' calculation, without [0] will be zero_indices = np.where(x[:-1]
# == 0)[0]
next_from_zero = x[zero_position + 1]  #Gives all position next to 0
max_from_zero = max(next_from_zero)  #Max value from all positions
print(f' NumPy realisation - {max_from_zero}')



x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
next_elements = []
for i in range(len(x) - 1):
    if x[i] == 0:
        next_elements.append(x[i+1])
# next_elements = [x[i+1] for i in range(len(x) - 1 if x[i] == 0] - For example if use List Comprehension
print(f' Python realisation - {max(next_elements)}')

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [39]:
# your code
x = [2, 2, 2, 3, 3, 3, 5]
# I can use set(x), but it will be sorted values. If x will [7,7,7,2,2,3,3,5] - It will be incorrect answer.
val = []
for num in x:
    if num not in val:
        val.append(num)

counts = [x.count(i) for i in val]
    
print(f'Python realisation - Counts: {counts}, Values: {val}')

import numpy as np

def rle_func(arr):
    n = len(arr)  #Length of array
    if n == 0:
        counts_n,values_n = np.array([]) #Conditions for empty array
    else:
        # Find position with changes values
        changes = arr[1:] != arr[:-1]  # Array with changes values whete "True" is changes

        #Get index with changes
        change_indices = np.nonzero(changes)[0]  
        # '-1' for added first element
        # 'n - 1' (n - is length array arr) for added the last position
        positions = np.concatenate([[-1], change_indices, [len(arr) - 1]])
        # calculation of length position
        counts_n = np.diff(positions)
        # Get starting values for each positions
        values_n = arr[positions[:-1] + 1]
    return values_n, counts_n

x = np.array([2, 2, 2, 3, 3, 3, 5])
values, counts = rle_func(x)
print(f'NumPy realisation - Counts: {counts}, Values: {values}')


Python realisation - Counts: [3, 3, 1], Values: [2, 3, 5]
NumPy realisation - Counts: [3 3 1], Values: [2 3 5]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [6]:
from math import sqrt

def euclidean_distances_no_numpy(X, Y):
    distances = []
    for x in X:
        row = []
        for y in Y:
            sum_squares = sum((xi - yi) ** 2 for xi, yi in zip(x, y))
            row.append(sqrt(sum_squares))
        distances.append(row)
    return distances

# Пример использования:
X_list = [[1, 2], [3, 4]]
Y_list = [[5, 6], [7, 8]]
print(euclidean_distances_no_numpy(X_list, Y_list))


import numpy as np

def euclidean_distances_numpy(X, Y):
    # Преобразуем списки в массивы NumPy, если они ещё не массивы
    X = np.array(X)
    Y = np.array(Y)
    # Вычисляем квадраты разностей и суммируем их
    diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
    dist = np.sqrt(np.sum(diff**2, axis=2))
    return dist

# Пример использования:
X_array = [[1, 2], [3, 4]]
Y_array = [[5, 6], [7, 8]]
print(euclidean_distances_numpy(X_array, Y_array))



[[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]


* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [7]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [8]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [37]:
crunchies_calories = 60
average_calories = calorie_stats.mean()
deference_calories = crunchies_calories-average_calories
print(f'Average calories of competitors: {round(average_calories,2)}')
print(f'Deference on calories between CrunchieMunchies product and competitors products: {round(deference_calories)}')

Average calories of competitors: 106.88
Deference on calories between CrunchieMunchies product and competitors products: -47


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [21]:
calorie_sorted = np.sort(calorie_stats)
print(f'Sorted calorie values: \n {calorie_sorted}')

Sorted calorie values: 
 [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [22]:
median_calories = np.median(calorie_stats)
print(f'Median calorie value: {median_calories}')

Median calorie value: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [29]:
nth_percentile = None
for pr in range(101):  # Interval up to 100%
    percentile_value = np.percentile(calorie_stats, pr)
    print(f'{pr}th percentile: {round(percentile_value)}') #Value after interpolation
    if percentile_value > 60:
        nth_percentile = pr
        print(f'Lower percentile, more then 60 calories is {pr}th percentile with values {percentile_value}')
        break



0th percentile: 50
1th percentile: 50
2th percentile: 50
3th percentile: 56
4th percentile: 70
Lower percentile, more then 60 calories is 4th percentile with values 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [40]:
count_greater_60 = np.count_nonzero(calorie_stats > 60)
more_calories = (count_greater_60 / len(calorie_stats)) * 100

print(f'Percent values more then 60: {round(more_calories,2)}%')

Percent values more then 60: 96.1%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [42]:
calorie_std = np.std(calorie_stats)
print(f'Standard deviation of calorie values: {round(calorie_std,2)}')

Standard deviation of calorie values: 19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [2]:
'''This reserch told us that most from competitors have greather calories than product Mycrunch. Value of calories in CrnchieMunchies less than median values. If this product will be same taysty than more half competitors product it can get more sall this products because with great taste. A lot of people want to great taste and low calorie - CrnchieMunchies will be great product for this tasks.'''

'This reserch told us that most from competitors have greather calories than product Mycrunch. Value of calories in CrnchieMunchies less than median values. If this product will be same taysty than more half competitors product it can get more sall this products because with great taste. A lot of people want to great taste and low calorie - CrnchieMunchies will be great product for this tasks.'